// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  navbar_data: dynamic(() => import("./NavbarData")),
  our_process: dynamic(() => import("./OurProcess")),
  our_services: dynamic(() => import("./OurServices")),
  right_process: dynamic(() => import("./RightProcess")),
  services: dynamic(() => import("./Services")),
  sets_apart: dynamic(() => import("./SetsApart")),
  testimonial: dynamic(() => import("./Testimonial")),
  top_section: dynamic(() => import("./TopSection")),
  tranform_ideas_section: dynamic(() => import("./TranformIdeasSection")),
  trusted_type: dynamic(() => import("./TrustedType")),
  user_profile: dynamic(() => import("./UserProfile")),
};
